name: Changelog

on:
  push:
    branches:
      - Development

jobs:
  Changelog:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Generate Changelog
        run: ./scripts/changelog.sh > CHANGELOG.md