name: Luacheck

on:
  push:
    branches:
      - Development

jobs:
  Luacheck:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          files: 'PhenomRaidTools/Source'
          config: 'https://github.com/PhenomDevel/PhenomRaidTools/blob/master/.luacheckrc'
          args: "--no-color -q"
          annotate: warning

      - name: Send Status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
        if: failure()
