name: Release Notification

on:
  push:
    tags:
      - "*"
      - "!**-alpha**"

jobs:
  notify_release:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Generate Changelog
        run: ./changelog.sh

      - name: Read CHANGELOG.md
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          trim: true
          path: ./CHANGELOG.md

      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "PhenomRaidTools"
          message: "${{ steps.changelog.outputs.content }}\n\nPlease note that it might take some time until the new release is available on the addon distribution applications. Please be a little patient :)"