name: Release

on:
  push:
    branches:
      - master
    tags:
      - "*"
      - "!**-alpha**"

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          files: 'PhenomRaidTools/Source'
          config: '.luacheckrc'
          args: "--no-color -q"
          annotate: warning

      - name: Clone project
        uses: actions/checkout@v1

      - name: Package and release
        uses: BigWigsMods/packager@v1

      - name: Send Status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
        if: failure()
